### ISSUE TITLE
[Native/Rust] Migrate PSXTimerController from C++ to Rust behind the existing C ABI

### ISSUE THREAD

**Issue by mao2009** [mao2009/PSXRecompStudio#486]
## Summary

Migrate the PS1 timer (Root Counter) controller, currently `src/PSXRecomp.Native/src/psx_timer.h`/`.cpp`, from C++ to Rust, following the exact pattern established by #484 (interrupt controller). Child of #471.

## Scope

- Replace `PSXTimerController`/`PSXTimerChannel` with a Rust module `rust/src/timer.rs` exporting the same operations as internal `extern "C"` functions (not managed-visible — consumed only by `src/psx_api.cpp`, exactly like `psx_interrupt.rs`/`psx_interrupt.h`).
- `PSXCore_*Timer*` signatures in `include/psx_core.h` / `NativeInterop.cs` do not change. `ABI_VERSION` does not change.
- State (`PSXTimerChannel` × 3) is `#[repr(C)]`, POD, passed/returned by value — no pointers, no allocation, mirroring the interrupt controller's state-passing model.
- Preserve exact documented semantics: per-timer COUNT/MODE/TARGET registers at `0x1F801100 + n*0x10`, clock-source divisors (Timer 2 `/8`), sync-line gating per psx-spx (including sync mode 3 arm-on-first-blank), target/overflow flags, pulse vs toggle IRQ behavior with one-shot re-arm on mode write, and read-MODE-clears-flags.
- Remove the C++ implementation in the same PR (FFI contract "definition of done").

## ABI preservation requirements

- No managed-visible signature or semantics change. `ABI_VERSION` unchanged (internal-only migration, same as #484).

## Ownership/lifetime design

- No heap allocation. `PSXTimerChannel`/timer array stored inline in `PSXCore` (Rust-side state passed by value into/out of each call), matching `PSXInterruptState`'s model.

## Panic/unsafe requirements

- Every export obeys `docs/development/rust-ffi-contract.md` sections 1-9. No `unsafe` should be needed at all (pure value semantics), matching interrupt controller. If any pointer surface is required, `catch_unwind` + `PSX_RUST_ERR_PANIC` containment applies.

## Removal of duplicate C++ authority

- `psx_timer.h`/`psx_timer.cpp` C++ implementation is deleted; `src/psx_api.cpp` and `psx_core.cpp` call the new Rust exports instead, via an internal header (new `psx_timer.h` becomes the internal declaration header for the Rust exports, like `psx_interrupt.h`).

## Equivalence tests

- Full port of existing timer semantics into Rust `#[cfg(test)]` unit tests (register decode, clock divisor, sync gating per mode, target/overflow flag + IRQ firing, one-shot re-arm, mode-write reset behavior).
- Existing native `test_psx_core.cpp` timer coverage continues to pass unchanged (behavior-preserving migration).

## Production-path proof

- `PSXCore_Step`/`PSXCore_Run` and any managed test exercising the real staged native artifact must continue to pass unchanged.

## Exclusions

- No behavior change to timer semantics. No changes to `psx_dma.h`/`psx_dma.cpp` or the interrupt controller.
- Does not implement #442's scheduling contract itself (CPU-cycle-driven tick/VBlank/IRQ orchestration) — only preserves the subsystem #442 will call into.

## Overlap constraints

- #442 (runtime scheduling) is expected to only *consume* this subsystem's existing `Tick`/`SetSyncLine`/`GetInterruptPending`/`ClearInterrupt` operations through the unchanged `PSXCore_*Timer*` C ABI, not modify `psx_timer.*` itself — this migration should not block or conflict with #442 landing in parallel.

Parent: #471
